### ISSUE TITLE
Regarding Custom Dataset

### ISSUE THREAD

**Issue by pytholic** [facebookresearch/votenet#131]
Hi. I have been doing research regarding point cloud object detection. However, all the architectures currently support only benchmark datasets and there is no proper guidance on how to prepare our own datasets. For example, I have some point clouds of patients and I want to detect some regions for medical purposes. However, I cannot find any guidance here or in other models as well to work with custom datasets. Will appreciate any guidance on this. Thanks!

**Comment by IliasMAOUDJ** [comment]
Hello,

You can find some tips [here](https://github.com/facebookresearch/votenet/blob/master/doc/tips.md). I created my own "custom_dataset" (CD) folder with modified python scripts for "CD_data.py" "CD_detection_dataset.py" "CD_utils.py" and "model_util_CD.py". I used the sunrgbd folder as a template since my annotations were very similar.

**Comment by pytholic** [comment]
@IliasMAOUDJ thank you for the reply. I have seen the link that you shared before. I had two main issues due to which I couldn't follow those steps. 

1) I was not sure which annotation tool to use to match sunrgbd format. Can you tell me which tool did you use? Also I am not sure if my point clouds are in upright coordinate system or not.

2) Most of the implementation also use real images and camera calib files in their implementation I think. However, I only have point cloud (mesh) data. So I was not sure how to work with it.

**Comment by IliasMAOUDJ** [comment]
1. My dataset is synthetic so I haven't used any tool. I used Trimesh to create the scenes and annotated directly with the properties of the objects. My point clouds weren't in upright coordinate system but since my objects could have any rotation it didn't matter much. I adapted the network to predict 3 rotations though.

2. The real images and calib are used only for the vizualisation I think (but I removed them anyway). I could train the network successfully without using those.

**Comment by vinayver198** [comment]
Hi @IliasMAOUDJ  ,
I also have a dataset, its not synthetic and has 3 rotations . When you trained the model, did you encounter any  perfornance reduction . I have not used votenet yet . Using frustum pointnet I encountered performance reduction  so just want to confirm before moving forward .

**Comment by madinwei** [comment]
> @IliasMAOUDJ thank you for the reply. I have seen the link that you shared before. I had two main issues due to which I couldn't follow those steps.
> 
> 1. I was not sure which annotation tool to use to match sunrgbd format. Can you tell me which tool did you use? Also I am not sure if my point clouds are in upright coordinate system or not.
> 2. Most of the implementation also use real images and camera calib files in their implementation I think. However, I only have point cloud (mesh) data. So I was not sure how to work with it.


@pytholic , hello. I am trying also to use my custom data. if you found which annotation too to use. please share with me if possible and thank you. Like you, I only have point cloud data. I am a bit novice in point cloud detection any suggestions or guides will help so much. 

and thank you as well  @IliasMAOUDJ . Your comment also clarifies for me that the training does not need the othe files in the sunrgbd.

**Comment by pytholic** [comment]
> > @IliasMAOUDJ thank you for the reply. I have seen the link that you shared before. I had two main issues due to which I couldn't follow those steps.
> > 
> > 1. I was not sure which annotation tool to use to match sunrgbd format. Can you tell me which tool did you use? Also I am not sure if my point clouds are in upright coordinate system or not.
> > 2. Most of the implementation also use real images and camera calib files in their implementation I think. However, I only have point cloud (mesh) data. So I was not sure how to work with it.
> 
> @pytholic , hello. I am trying also to use my custom data. if you found which annotation too to use. please share with me if possible and thank you. Like you, I only have point cloud data. I am a bit novice in point cloud detection any suggestions or guides will help so much.
> 
> and thank you as well @IliasMAOUDJ . Your comment also clarifies for me that the training does not need the othe files in the sunrgbd.

HI @madinwei .
It has been a while since I worked on it so I don't recall all the details. These days I am more focused on Visual SLAM.

I did not use `votenet` in the end though.
You can check my repo [here](https://github.com/pytholic/3dFacialPartSegmentation/tree/main/Deep%20Learning). You can also visit the original links from the `README.md`.

Hope it helps!

**Comment by madinwei** [comment]
> HI @madinwei . It has been a while since I worked on it so I don't recall all the details. These days I am more focused on Visual SLAM.
> 
> I did not use `votenet` in the end though. You can check my repo [here](https://github.com/pytholic/3dFacialPartSegmentation/tree/main/Deep%20Learning). You can also visit the original links from the `README.md`.
> 
> Hope it helps!

I am very grateful for your reply @pytholic. Since you didn't use votenet, can you recommend to me, which model should I use for point cloud detection?
regarding your repo, they are very helpful, thank you so much. I used that Pointnet Colab notebook before to know how to use Pointnet. However, I didn't know how to make the point net do object detection. I have checked the original links README.md before but didn't find any information on the annotation tool, I will check them again. if you can direct me to it that will be great.

Again thank you so much, I hope I didn't bother you with my question.
