### ISSUE TITLE
Why do some categories score so low?

### ISSUE THREAD

**Issue by WangZhouTao** [facebookresearch/votenet#15]
Hi，I am reading this paper and find some problem. Do you know why are the mAP scores of the dresser, bookshelf and desk is very low? Is it due to data set problems or these objects are more difficult to detect?

**Comment by charlesq34** [comment]
There are several possible reasons. For desks, they may be easily confused with tables -- sometimes whether the furniture is desk or table totally depend on its function instead of its shape. For bookshelves, they are often occluded; many of the bookshelves are also not annotated in the dataset. There are also some missed annotations for dressers and nightstands while they are often occluded as well.

You can try to visualize the data to get more insights too.

**Comment by WangZhouTao** [comment]
thank for your reply，your answer is help me a lot.
