### ISSUE TITLE
Why set FLAG ‘per_class_proposal’ as true?

### ISSUE THREAD

**Issue by BigDeviltjj** [facebookresearch/votenet#17]
HI, why set __per_class_proposal__ as true in evaluation time? When it is true, all boxes would bed added to each class with different score.

Why it is helpful to achieve better results?

**Comment by charlesq34** [comment]
Hi @BigDeviltjj 

In the demo we set the `per_class_proposal` flag as False, to give us more clear visualization results.

In AP metric evaluation setting the flag as True helps because there are some confusing classes such as desks and tables, dressers and nightstands, sofas and chairs etc. Generating proposal boxes for all classes increases recall significantly (also presented in the appendix of the paper).

**Comment by BigDeviltjj** [comment]
@charlesq34 Thx for answering my question. It is a brilliant way to increase recall!
