### ISSUE TITLE
does votenet suit for lidar point cloud detection? 

### ISSUE THREAD

**Issue by godspeed1989** [facebookresearch/votenet#8]
Hi,
Thanks for your good work.
I am curious that does votenet suit for object detection in lidar e.g. kitti benchmark?
Whether the lidar point cloud is too sparse to vote out good candidates

**Comment by charlesq34** [comment]
Good question!

It is possible to apply a similar idea to KITTI. I did have some initial experiments with some positive signals. However due to the time constraint we didn’t go deep into this part.

As lidar points are more sparse, the signal to noise ratio (rate of positive votes to negative votes) is lower – some filtering or pre-segmentation may be necessary to make it work really well.

**Comment by godspeed1989** [comment]
Thanks for your reply.
I think the pipeline with pre-segmentation like PointRCNN may help. Or we can upsample/completion point cloud firstly.

**Comment by gigadeplex** [comment]
@godspeed1989 did you get this working? if so how were the results?

**Comment by godspeed1989** [comment]
@gigadeplex Not yet, it is just a idea now.
