### ISSUE TITLE
Results on the val set

### ISSUE THREAD

**Issue by NUAAXQ** [facebookresearch/votenet#9]
Hi, as reported in the paper, the results are tested on the val set for both SUNRGBD and ScanNet dataset. The evaluation is ran every 10 epoches, but the result varies over a small range when the learning is coveraged.
My question is how to choose the final result to report? The highest one or an average value on some epoches, or something esle?

**Comment by charlesq34** [comment]
Hi @NUAAXQ 

Due to the limited size of the dataset, the mAP results do have some variances. I don't think there is any common protocol to report the numbers now (which is an issue). The variance at least comes from three sources, models from different trainings (with different init), models at different epochs and results from different evaluations (due the randomness in points subsampling).

In our case, we reported numbers of a specific model after its convergence, which is okay as our model has significantly higher mAP so there won't be confusion on which model is better.

In the general case, I would personally recommend take a converged model (e.g. trained after 180 epochs) and evaluate the model 3 times and report their average results.

**Comment by NUAAXQ** [comment]
@charlesq34 The answer gives more than my question! Thanks very much for your kindly sharing!
